#define LANGUAGENAME_TEXT "Français"
#define UNIT_MONTHS_TEXT "Mois"
#define UNIT_DAYS_TEXT "Jours"
#define UNIT_HOUR_TEXT "h"
#define UNIT_MIN_TEXT "min"
#define UNIT_SEC_TEXT "s"
#define UNIT_DEG_TEXT "&deg;C"
#define UNIT_PERC_TEXT "&#037;"
#define UNIT_RPM_TEXT "tr/min"
#define UNIT_KW_TEXT "kW"
#define UNIT_KWH_TEXT "kWh"
#define UNIT_KWHM3_TEXT "kWh/m³"
#define UNIT_CURR_TEXT "&#181;A"
#define UNIT_BAR_TEXT "bar"
#define UNIT_VOLT_TEXT "V"
#define UNIT_GRADIENT_TEXT "min/K"
#define UNIT_GRADIENTKS_TEXT "K/s"
#define UNIT_INTEGRAL_TEXT "Kmin"
#define UNIT_TEMP_PER_MIN_TEXT "&deg;C/min"
#define UNIT_CEL_MIN_TEXT "&deg;Cmin"
#define UNIT_LITERPERHOUR_TEXT "l/h"
#define UNIT_LITERPERMIN_TEXT "l/min"

#define ENUM_CAT_00_TEXT "Date et heure"
#define ENUM_CAT_01_TEXT "Unité de contrôle"
#define ENUM_CAT_02_TEXT "Sans fil"
#define ENUM_CAT_03_TEXT "Programme horaire 1"
#define ENUM_CAT_04_TEXT "Programme horaire 2"
#define ENUM_CAT_05_TEXT "Programme horaire 3/P"
#define ENUM_CAT_06_TEXT "Programme horaire 4"
#define ENUM_CAT_07_TEXT "Programme horaire 5"
#define ENUM_CAT_08_TEXT "Programme vacances 1"
#define ENUM_CAT_09_TEXT "Programme vacances 2"
#define ENUM_CAT_0a_TEXT "Programme vacances P"
#define ENUM_CAT_0b_TEXT "Circuit chaud 1"
#define ENUM_CAT_0c_TEXT "Circuit froid 1"
#define ENUM_CAT_0d_TEXT "Circuit chaud 2"
#define ENUM_CAT_0e_TEXT "Circuit froid 2"
#define ENUM_CAT_0f_TEXT "Circuit chaud 3/P"
#define ENUM_CAT_10_TEXT "Eau chaude sanitaire"
#define ENUM_CAT_11_TEXT "Circuit consommateur 1"
#define ENUM_CAT_12_TEXT "Circuit consommateur 2"
#define ENUM_CAT_13_TEXT "Circuit de piscine"
#define ENUM_CAT_14_TEXT "Circulateur"
#define ENUM_CAT_15_TEXT "Piscine"
#define ENUM_CAT_16_TEXT "Contrôleur primaire/pompe d'alimentation 1"
#define ENUM_CAT_17_TEXT "Contrôleur primaire/pompe d'alimentation 2"
#define ENUM_CAT_18_TEXT "Chaudière"
#define ENUM_CAT_19_TEXT "Sitherm Pro"
#define ENUM_CAT_1a_TEXT "Pompe à chaleur"
#define ENUM_CAT_1b_TEXT "Compteur d'énergie"
#define ENUM_CAT_1c_TEXT "Cascade"
#define ENUM_CAT_1d_TEXT "Source auxiliaire de chaleur"
#define ENUM_CAT_1e_TEXT "Solaire"
#define ENUM_CAT_1f_TEXT "Chaudière à combustible solide"
#define ENUM_CAT_20_TEXT "Accumulateur tampon"
#define ENUM_CAT_21_TEXT "Accumulateur ECS"
#define ENUM_CAT_22_TEXT "Charge directe ECS"
#define ENUM_CAT_23_TEXT "Fonctions générales"
#define ENUM_CAT_24_TEXT "Configuration"
#define ENUM_CAT_25_TEXT "Bus LPB"
#define ENUM_CAT_26_TEXT "Défaut"
#define ENUM_CAT_27_TEXT "Maintenance/Fonctions avancées"
#define ENUM_CAT_28_TEXT "Configuration des modules d'extension"
#define ENUM_CAT_29_TEXT "Tests des entrées/sorties"
#define ENUM_CAT_2a_TEXT "Etat"
#define ENUM_CAT_2b_TEXT "Diagnostic cascade"
#define ENUM_CAT_2c_TEXT "Diagnostic générateur"
#define ENUM_CAT_2d_TEXT "Diagnostic consommateurs"
#define ENUM_CAT_2e_TEXT "Coffret de sécurité"
#define ENUM_CAT_2f_TEXT "Défini par l'utilisateur"
#define ENUM_CAT_30_TEXT "Bus PPS"
#define ENUM_CAT_31_TEXT "Catégorie inconnue"

#define MENU_TEXT_HFK "Fonctions chauffage"
#define MENU_TEXT_SNS "Capteurs"
#define MENU_TEXT_SN1 "Capteurs DS18B20"
#define MENU_TEXT_SN2 "Capteurs DHT22"
#define MENU_TEXT_CHK "Vérifier les nouveaux paramètres"
#define MENU_TEXT_DLG "Afficher les données du fichier journal"
#define MENU_TEXT_SLG "Afficher les Graphiques du fichier journal"
#define MENU_TEXT_CFG "Réglages"
#define MENU_TEXT_URL "Commandes URL"
#define MENU_TEXT_HWT "Mode d'emploi"
#define MENU_TEXT_FAQ "FAQ"
#define MENU_TEXT_YES "Oui"
#define MENU_TEXT_NO "Non"
#define MENU_TEXT_ON "Marche"
#define MENU_TEXT_OFF "Arrêt"
#define MENU_TEXT_OPEN "Ouvert"
#define MENU_TEXT_CLOSE "Fermé"
#define MENU_DESC_HFK "Affiche les paramètres de votre système de chauffage et vous permet de les modifier. Ces paramètres sont répartis en catégories sur lesquelles vous pouvez cliquer."
#define MENU_DESC_CFG "Affiche les options de configuration de BSB-LAN. Ces paramètres peuvent être modifiés à l'aide des commandes URL étendues."
#define MENU_DESC_URL "Affiche la liste des commandes étendues que vous pouvez saisir dans la ligne d'adresse du navigateur. Ces commandes sont également utiles pour relier BSB-LAN à certains systèmes de domotique tels que FHEM."
#define MENU_TEXT_VB1 "Mode verbeux activé!"
#define MENU_TEXT_VB2 "Mode verbeux désactivé!"
#define MENU_TEXT_VB3 "Le mode verbeux affecte à la fois la console série de l'Arduino et (en option) la journalisation des données du bus sur la carte microSD, ce qui peut rapidment remplir votre carte! La sortie html reste inchangée."
#define MENU_TEXT_SR1 "Moniteur série activé!"
#define MENU_TEXT_SR2 "Moniteur série désactivé!"
#define MENU_TEXT_SR3 "Seule la sortie série est affectée."
#define MENU_TEXT_ER1 "ERREUR: Paramètre invalide!"
#define MENU_TEXT_ER2 "ERREUR: Valeur invalide!"
#define MENU_TEXT_ER3 "ERREUR: Le réglage a échoué!"
#define MENU_TEXT_ER4 "Paramètre en lecture seule."
#define MENU_TEXT_ER5 "ERREUR: Type incorrect!"
#define MENU_TEXT_ER6 "ERREUR: Ligne introuvable!"
#define MENU_TEXT_ER7 "ERREUR: Broche GPIO protégée!"
#define MENU_TEXT_BST "Statistiques du brûleur"
#define MENU_TEXT_BRS "Temps de fonctionnement chaudière et ECS mis à zéro"
#define MENU_TEXT_24A "Moyennes sur 24h"
#define MENU_TEXT_24N "Ajouter des paramètres aux moyennes"
#define MENU_TEXT_DTR ": le fichier a été supprimé puis recréé."
#define MENU_TEXT_DTD "Télécharger les données"
#define MENU_TEXT_DTF "Impossible de créer le fichier datalog.txt!"
#define MENU_TEXT_DTO "Impossible d'ouvrir le fichier datalog.txt!"
#define MENU_TEXT_RAM "Mémoire libre"
#define MENU_TEXT_BUS "Bus système"
#define MENU_TEXT_BRW "Lecture/Ecriture"
#define MENU_TEXT_BRO "Lecture seule"
#define MENU_TEXT_OWP "Broche de bus 1-Wire"
#define MENU_TEXT_DHP "Broche de bus DHT22"
#define MENU_TEXT_EXP "Broches GPIO protégées"
#define MENU_TEXT_MAC "Adresse MAC"
#define MENU_TEXT_LGP "Enregistrement des paramètres suivants toutes les"
#define MENU_TEXT_SEC "Secondes"
#define MENU_TEXT_BZ1 "Durée de fonctionnement du brûleur, allure 1"
#define MENU_TEXT_BT1 "Nombre d'allumages du brûleur, allure 1"
#define MENU_TEXT_BZ2 "Durée de fonctionnement du brûleur, allure 2"
#define MENU_TEXT_BT2 "Nombre d'allumages du brûleur, allure 2"
#define MENU_TEXT_TZ1 "Durée de fonctionnement ECS"
#define MENU_TEXT_TT1 "Nombre d'allumages ECS"
#define MENU_TEXT_MXI "MAX! T° réelle"
#define MENU_TEXT_MXS "MAX! T° de consigne"
#define MENU_TEXT_MXV "MAX! Ouverture valve"
#define MENU_TEXT_MXN "Aucune donnée MAX! n'a encore été reçue."
#define MENU_TEXT_BDT "Télégrammes de données BSB (quel que soit l'intervalle)"
#define MENU_TEXT_BUT "Enregistrer seulement les télégrammes inconnus"
#define MENU_TEXT_MMD "Mode moniteur"
#define MENU_TEXT_VBL "Niveau de verbosité"
#define MENU_TEXT_AVT "Calcul des moyennes sur 24h pour les paramètres suivants"
#define MENU_TEXT_LBO "Enregistrer seulement les télégrammes de diffusion (broadcast)"
#define MENU_TEXT_LGI "Nouvel intervalle d'enregistrement"
#define MENU_TEXT_LGN "Nouveaux paramètres à enregistrer"
#define MENU_TEXT_QSC "Rechercher des appareils"
#define MENU_TEXT_QFD "Adresse de l'appareil trouvée"
#define MENU_TEXT_QFA "La requête de l'appareil a échoué"
#define MENU_TEXT_QRT "Adresse de l'appareil de test"
#define MENU_TEXT_QST "Lancer le test"
#define MENU_TEXT_QTE "Test terminé"
#define MENU_TEXT_QFE "Fini"
#define MENU_TEXT_TOC "Manuel"
#define MENU_TEXT_UPT "Uptime"
#define MENU_TEXT_VER "Version"
#define MENU_TEXT_MOD "Modules installés"
#define MENU_TEXT_NVS "Rechercher une version plus récente"
#define MENU_TEXT_NVA "Nouvelle version trouvée"
#define MENU_TEXT_NVN "Votre version de BSB-Lan est à jour."
#define MENU_TEXT_LOT "Journal des télégrammes"

#define STR0_TEXT "Date/Heure"
#define STR1_TEXT "Heures/Minutes"
#define STR2_TEXT "Jour/Mois"
#define STR3_TEXT "Année"
#define STR5_TEXT "Début de l'heure d'été (Jour/Mois)"
#define STR6_TEXT "Fin de l'heure d'été (Jour/Mois)"
#define STR20_TEXT "Sélection de la langue"
#define STR21_TEXT "Afficher une opération spéciale"
#define STR22_TEXT "Info"
#define STR23_TEXT "Affichage d'erreur"
#define STR25_TEXT "Contraste d'affichage"
#define STR26_TEXT "Verrouillage de l'utilisation"
#define STR27_TEXT "Verrouillage de la programmation"
#define STR28_TEXT "Réglage direct de l'unité de commande"
#define STR29_TEXT "Unités"
#define STR30_TEXT "Sauvegarder le réglage de base de l'unité de commande"
#define STR31_TEXT "Activer le réglage de base de l'unité de commande"
#define STR40_TEXT "Utilisé comme"
#define STR42_TEXT "Unité d'ambiance 1"
#define STR42_2_TEXT "Effet de l'unité d'ambiance sur les circuits de chauffage"
#define STR44_TEXT "Opération circuit de chauffage 2"
#define STR46_TEXT "Opération circuit de chauffage P"
#define STR48_TEXT "Effet du bouton de présence"
#define STR54_TEXT "Correction de la sonde d'ambiance"
#define STR70_TEXT "Version du firmware"
#define STR71_TEXT "Type d'unité d'ambiance"
#define STR120_TEXT "Liaison"
#define STR121_TEXT "Mode test"
#define STR130_TEXT "État de l'unité d'ambiance 1"
#define STR131_TEXT "État de l'unité d'ambiance 2"
#define STR132_TEXT "État de l'unité d'ambiance P"
#define STR133_TEXT "État de la sonde extérieure P"
#define STR134_TEXT "État du répéteur P"
#define STR135_TEXT "État de l'unité de contrôle 1"
#define STR136_TEXT "État de l'unité de contrôle 2"
#define STR137_TEXT "État de l'unité de contrôle P"
#define STR138_TEXT "État de l'unité de service"
#define STR140_TEXT "Supprimer tous les appareils"
#define STR500_TEXT "Lu"
#define STR501_TEXT "Ma"
#define STR502_TEXT "Me"
#define STR503_TEXT "Je"
#define STR504_TEXT "Ve"
#define STR505_TEXT "Sa"
#define STR506_TEXT "Di"
#define STR516_TEXT "Valeurs par défaut"
#define STR632_TEXT "Début de la période 1 (Jour/Mois)"
#define STR633_TEXT "Fin de la période 1 (Jour/Mois)"
#define STR634_TEXT "Début de la période 2 (Jour/Mois)"
#define STR635_TEXT "Fin de la période 2 (Jour/Mois)"
#define STR636_TEXT "Début de la période 3 (Jour/Mois)"
#define STR637_TEXT "Fin de la période 3 (Jour/Mois)"
#define STR638_TEXT "Début de la période 4 (Jour/Mois)"
#define STR639_TEXT "Fin de la période 4 (Jour/Mois)"
#define STR640_TEXT "Début de la période 5 (Jour/Mois)"
#define STR641_TEXT "Fin de la période 5 (Jour/Mois)"
#define STR642_TEXT "Début de la période 6 (Jour/Mois)"
#define STR643_TEXT "Fin de la période 6 (Jour/Mois)"
#define STR644_TEXT "Début de la période 7 (Jour/Mois)"
#define STR645_TEXT "Fin de la période 7 (Jour/Mois)"
#define STR646_TEXT "Début de la période 8 (Jour/Mois)"
#define STR647_TEXT "Fin de la période 8 (Jour/Mois)"
#define STR648_TEXT "Niveau de fonct. pendant vacances"
#define STR700_TEXT "Mode de fonctionnement"
#define STR701_TEXT "Bouton de présence (absence temporaire)"
#define STR709_TEXT "Consigne de confort minimum"
#define STR710_TEXT "Consigne de confort"
#define STR711_TEXT "Consigne de confort maximum"
#define STR712_TEXT "Consigne réduite"
#define STR714_TEXT "Consigne hors gel"
#define STR720_TEXT "Pente de la courbe de chauffe"
#define STR721_TEXT "Translation de la courbe de chauffe"
#define STR726_TEXT "Adaptation courbe de chauffe"
#define STR730_TEXT "T° de bascule été/hiver"
#define STR732_TEXT "Limite de chauffe journalière"
#define STR733_TEXT "Extension de la limite de chauffe journalière"
#define STR734_TEXT "Régler le réduit avec la minuterie"
#define STR740_TEXT "Consigne de départ minimale"
#define STR741_TEXT "Consigne de départ maximale"
#define STR742_TEXT "Consigne de départ thermostat d'ambiance"
#define STR744_TEXT "Allumage proportionnel au thermostat d'ambiance"
#define STR746_TEXT "Retarder la demande de chaleur"
#define STR750_TEXT "Facteur d'influence T° ambiante"
#define STR760_TEXT "Limitation de T° ambiante"
#define STR761_TEXT "Limite de chauffage du régulateur d'ambiance"
#define STR770_TEXT "Chauffe accélérée"
#define STR780_TEXT "Réduction accélérée"
#define STR781_TEXT "Facteur de réduction accélérée"
#define STR790_TEXT "Optimisation heure de relance, avance maxi"
#define STR791_TEXT "Optimisation heure de coupure, avance maxi"
#define STR794_TEXT "Gradient de chauffe"
#define STR800_TEXT "Début relèvement consigne réduite"
#define STR801_TEXT "Fin relèvement consigne réduite"
#define STR809_TEXT "Fonctionnement continu de la pompe"
#define STR810_TEXT "Protection hors gel de la pompe"
#define STR812_TEXT "T° hors gel"
#define STR820_TEXT "Protection de la pompe contre la surchauffe"
#define STR830_TEXT "Seuil supérieur de la vanne mélangeuse"
#define STR831_TEXT "Seuil inférieur de la vanne mélangeuse"
#define STR832_TEXT "Type d'actionneur (2 points, 3 points)"
#define STR833_TEXT "Différentiel de commutation 2 points"
#define STR834_TEXT "Temps de course de l'actionneur"
#define STR835_TEXT "Bande proportionnelle de la vanne mélangeuse Xp"
#define STR836_TEXT "Temps de réinitialisation de la vanne mélangeuse Tn"
#define STR850_TEXT "Fonction de séchage dalle"
#define STR851_TEXT "Séchage dalle: Consigne manuelle"
#define STR855_TEXT "Séchage dalle: Consigne de départ"
#define STR856_TEXT "Séchage dalle: Durée actuelle (jours)"
#define STR857_TEXT "Séchage dalle: Durée totale (jours)"
#define STR861_TEXT "Diminution de la surchauffe"
#define STR864_TEXT "Verrouiller le gain du signal"
#define STR870_TEXT "Avec stockage tampon"
#define STR872_TEXT "Avec régulateur primaire/pompe d'alimentation"
#define STR880_TEXT "Réduction vitesse circulateur circuit de chauffage 1"
#define STR881_TEXT "Vitesse de départ"
#define STR882_TEXT "Vitesse minimale de la pompe"
#define STR883_TEXT "Vitesse maximale de la pompe"
#define STR884_TEXT "Allure pompe chaudière au point de conception"
#define STR885_TEXT "Pompe modulante TRM minimum"
#define STR886_TEXT "Temp. extérieure pour besoins calorifiques maxi"
#define STR886_2_TEXT "Vitesse maximale de la pompe OEM"
#define STR887_TEXT "Consigne chaudière pour T° extérieure normale"
#define STR888_TEXT "Limite pour surélévation temp. De la régul. Dt"
#define STR888_2_TEXT "Courbe caractéristique corr à 50% de vitesse"
#define STR889_TEXT "Constante de temps du filtre"
#define STR890_TEXT "Consigne de débit corr"
#define STR894_TEXT "Delta départ/retour pour T° extérieure normale"
#define STR895_TEXT "Delta départ/retour Maximum"
#define STR898_TEXT "Commutation du niveau de fonctionnement"
#define STR904_TEXT "Consigne de protection"
#define STR907_TEXT "Libération"
#define STR908_TEXT "Consigne de départ à TA 25°C"
#define STR909_TEXT "Consigne de départ à TA 35°C"
#define STR912_TEXT "Limite de refroidissement à TA"
#define STR913_TEXT "Période de verrouillage après fin de chauffe"
#define STR914_TEXT "Limite de refroidissement quotidienne"
#define STR918_TEXT "Début de la compensation d'été en TA"
#define STR919_TEXT "Fin  de la compensation d'été en TA"
#define STR920_TEXT "Augmentation de la consigne d'été"
#define STR923_TEXT "Consigne de départ mini à TA 25°C"
#define STR924_TEXT "Consigne de départ mini à TA 35°C"
#define STR933_TEXT "Limite de refroidissement du régulateur d'ambiance"
#define STR945_TEXT "Vanne mélangeuse en mode chauffage"
#define STR946_TEXT "Période de verrouillage du moniteur de point de rosée"
#define STR947_TEXT "Augmentation de la consigne de débit hygro"
#define STR950_TEXT "Différentiel point de rosée"
#define STR963_TEXT "Avec régulateur primaire/pompe d'alimentation"
#define STR1030_TEXT "T° de bascule été/hiver"
#define STR1042_TEXT "Consigne de départ de l'unité d'ambiance"
#define STR1109_TEXT "Fonctionnement continu de la pompe du circuit de chauffage 2"
#define STR1150_TEXT "Fonction de séchage dalle"
#define STR1151_TEXT "Séchage dalle: Consigne manuelle"
#define STR1155_TEXT "Séchage dalle: Consigne de départ"
#define STR1156_TEXT "Séchage dalle: Durée actuelle (jours)"
#define STR1157_TEXT "Séchage dalle: Durée totale (jours)"
#define STR1180_TEXT "Réduction vitesse circulateur circuit de chauffage 2"
#define STR1600_TEXT "Régime ECS"
#define STR1610_TEXT "Consigne nominale de T° ECS"
#define STR1612_TEXT "Consigne réduite de T° ECS"
#define STR1614_TEXT "Consigne réduite de T° ECS maximum"
#define STR1620_TEXT "Libération ECS"
#define STR1630_TEXT "Priorité ECS"
#define STR1640_TEXT "Fonction anti-légionelle"
#define STR1641_TEXT "Fonction anti-légionelle: Périodicité"
#define STR1642_TEXT "Fonction anti-légionelle: Jour"
#define STR1644_TEXT "Fonction anti-légionelle: Heure"
#define STR1645_TEXT "Fonction anti-légionelle: Consigne"
#define STR1646_TEXT "Fonction anti-légionelle: Durée"
#define STR1647_TEXT "Fonction anti-légionelle: Fonctionnement circulateur"
#define STR1660_TEXT "Libération de la pompe de bouclage ECS"
#define STR1661_TEXT "Fonctionnement cyclique pompe de bouclage ECS"
#define STR2201_TEXT "Blocage générateur"
#define STR2210_TEXT "T° de chaudière mini"
#define STR2212_TEXT "T° de chaudière maxi"
#define STR2440_TEXT "Degré modul. Maxi en mode chauffage"
#define STR2441_TEXT "Vitesse rotation ventil. maxi  mode chauffage"
#define STR2442_TEXT "Puissance pendant tempo. Régulateur active"
#define STR2443_TEXT "Démar. Puissance si régul. Libéré av Ch-eau inst"
#define STR2451_TEXT "Temps de pause minimal du brûleur"
#define STR2452_TEXT "Diff. De rég. Max sans interrup pause mini"
#define STR2453_TEXT "Temporisation  régulateur après mise en service"
#define STR2454_TEXT "Différentiel chaudière"
#define STR2455_TEXT "Différence coupure mini chaudière"
#define STR2456_TEXT "Diff. de coupure maxi chaudière"
#define STR2471_TEXT "Temporisation d'arrêt de la pompe"
#define STR2472_TEXT "T° retard à l'arrêt pompe ECS"
#define STR2521_TEXT "T° enclenchement antigel chaudière"
#define STR2522_TEXT "T° de coupure antigel chaudière"
#define STR3810_TEXT "Différence de T° Marche solaire"
#define STR3811_TEXT "Différence de T° Arrêt solaire"
#define STR3812_TEXT "T° de charge minimale"
#define STR3831_TEXT "Temps de marche min. de la pompe du collecteur"
#define STR3840_TEXT "T° anti-gel capteur solaire"
#define STR3850_TEXT "Temp. protection contre surchauffe collecteur"
#define STR3860_TEXT "T° d'évaporation caloporteur"
#define STR4721_TEXT "Différentiel blocage automatique du générateur"
#define STR4722_TEXT "Diff.  temp. Tampon/CC jusqu'à libér. Producteur"
#define STR5019_TEXT "Elévation consigne p.recharge accumulateur"
#define STR5020_TEXT "Surélévation T° de départ ECS"
#define STR5050_TEXT "T° de charge maxi ballon ECS"
#define STR5055_TEXT "Temp. min. refroidissem. adiab. Ballon ECS"
#define STR5100_TEXT "Allure pompe mini pour charge cont. ballon strat"
#define STR5020_TEXT "Surélévation T° de départ ECS"
#define STR5400_TEXT "Consigne pour T° préparation ECS"
#define STR5430_TEXT "Différentiel enclenchement mode ECS (sonde 1)"
#define STR5431_TEXT "Différentiel coupur mini mode ECS (sonde 1)"
#define STR5432_TEXT "Différentiel coupure maxi mode ECS (sonde 1)"
#define STR5433_TEXT "Différentiel enclenchement mode ECS (sonde 2)"
#define STR5434_TEXT "Différentiel coupure mini mode ECS (sonde 2)"
#define STR5435_TEXT "Différentiel coupure maxi mode ECS (sonde 2)"
#define STR5450_TEXT "Seuil de fin d'un tirage ECS pour ch-eau inst."
#define STR5451_TEXT "Seuil pour tirage ECS avec ch-ins en confort"
#define STR5452_TEXT "Seuil pour tirage ECS avec ch-ins en mode Ch."
#define STR5453_TEXT "Correction consigne régulation confort à 40°C"
#define STR5454_TEXT "Correction consigne régulation confort à 60°C"
#define STR5455_TEXT "Correction consigne régulation sortie à 40°C"
#define STR5456_TEXT "Correction consigne régulation sortie à 60°C"
#define STR5480_TEXT "Temps Confort ch-eau après tirage sans dem. Ch."
#define STR5481_TEXT "Temps de confort Ch-eau si dem. Ch. Active"
#define STR5482_TEXT "Durée FlowSwitch ECS fermé"
#define STR5483_TEXT "Durée FlowSwitch Confort ECS fermé"
#define STR5486_TEXT "Tempo régulateur si modul."
#define STR5487_TEXT "Arrêt ret. pompe en confort CHINS si brûl. HORS"
#define STR5488_TEXT "Arrêt ret. pompe en confort CHINS si brûl. HORS"
#define STR5701_TEXT "Type d'installation"
#define STR5710_TEXT "Circuit de chauffage 1"
#define STR5715_TEXT "Circuit de chauffage 2"
#define STR5732_TEXT "Durée arrêt pompe si changeover CH vers ECS"
#define STR5733_TEXT "Tempo. Arrêt pompe si changeover CH->ECS"
#define STR5761_TEXT "Demandes de chauffage avec soutien par Q8"
#define STR5920_TEXT "Sortie programmable K2"
#define STR5921_TEXT "Défaut K2 sur K1"
#define STR5922_TEXT "Sortie fonction 1 Clip-In Relais"
#define STR5923_TEXT "Sortie fonction 2 Clip-In Relais"
#define STR5924_TEXT "Sortie fonction 3 Clip-In Relais"
#define STR5926_TEXT "Configuration sortie 1"
#define STR5927_TEXT "Configuration sortie 2"
#define STR5928_TEXT "Configuration sortie 3"
#define STR5950_TEXT "Entrée H1 sélection de fonction"
#define STR5957_TEXT "Fonction modem"
#define STR5970_TEXT "Configuration thermostat d'ambiance 1"
#define STR5971_TEXT "Configuration thermostat d'ambiance 2"
#define STR5973_TEXT "Fonction Entrée RelCl"
#define STR5975_TEXT "Limite T° pour consigne prescrite ext."
#define STR5976_TEXT "Limite Inf. signal entrée pour demande ext."
#define STR6110_TEXT "Constante de temps du bâtiment"
#define STR6112_TEXT "Gradient modèle d'ambiance"
#define STR6120_TEXT "Hors gel de l'installation"
#define STR6127_TEXT "Temps de dégommage pompes/vanne dérivation"
#define STR6220_TEXT "Version du logiciel"
#define STR6225_TEXT "Famille d'appareil"
#define STR6226_TEXT "Variante d'appareil"
#define STR6227_TEXT "Version OV d'appareil"
#define STR6230_TEXT "Configuration du régulateur 0"
#define STR6240_TEXT "Configuration du régulateur 1"
#define STR6250_TEXT "Configuration du régulateur 2"
#define STR6260_TEXT "Configuration du régulateur 3"
#define STR6270_TEXT "Configuration du régulateur 4"
#define STR6300_TEXT "Configuration du régulateur 7"
#define STR6330_TEXT "Configuration du régulateur 10"
#define STR6604_TEXT "Sélection fonction Alimentation Bus"
#define STR6605_TEXT "Etat de l'alimentation Bus"
#define STR6625_TEXT "Affectation d' ECS"
#define STR6640_TEXT "Source de l'heure"
#define STR6705_TEXT "Code de diagnostic interne"
#define STR6706_TEXT "Valeur actuelle de la phase de dérangement"
#define STR6710_TEXT "Réinitialiser relais d'alarme"
#define STR6711_TEXT "Réinitialiser pompe à chaleur"
#define STR6740_TEXT "Alarme T° départ 1"
#define STR6741_TEXT "Alarme T° départ 2"
#define STR6742_TEXT "Alarme T° départ 3"
#define STR6743_TEXT "Alarme T° chaudière"
#define STR6745_TEXT "Alarme T° ECS"
#define STR6746_TEXT "Alarme T° départ refroidissement 1"
#define STR6747_TEXT "Alarme T° départ refroidissement 2"
#define STR6800_2_TEXT "Historique 1"
#define STR6801_2_TEXT "Historique 1 Message erreur"
#define STR6805_2_TEXT "SW Code diag. 1"
#define STR6806_2_TEXT "FA Phase 1"
#define STR6810_2_TEXT "Historique 2"
#define STR6811_2_TEXT "Code erreur 2"
#define STR6813_2_TEXT "Historique 2 Message erreur"
#define STR6815_2_TEXT "SW Code diag. 2"
#define STR6816_2_TEXT "FA Phase 2"
#define STR6820_2_TEXT "Historique 3"
#define STR6821_TEXT "Code erreur 3"
#define STR6823_2_TEXT "Historique 3 Message erreur"
#define STR6825_TEXT "SW Code diag. 3"
#define STR6826_TEXT "FA Phase 3"
#define STR6830_TEXT "Historique 4"
#define STR6831_TEXT "Code erreur 4"
#define STR6833_2_TEXT "Historique 4 Message erreur"
#define STR6835_TEXT "SW Code diag. 4"
#define STR6836_TEXT "FA Phase 4"
#define STR6840_2_TEXT "Historique 5"
#define STR6843_2_TEXT "Historique 5 Message erreur"
#define STR6845_TEXT "SW Code diag. 5"
#define STR6846_TEXT "FA Phase 5"
#define STR6855_TEXT "SW Code diag. 6"
#define STR6856_TEXT "FA Phase 6"
#define STR6865_TEXT "SW Code diag. 7"
#define STR6866_TEXT "FA Phase 7"
#define STR6875_TEXT "SW Code diag. 8"
#define STR6876_TEXT "FA Phase 8"
#define STR6885_TEXT "SW Code diag. 9"
#define STR6886_TEXT "FA Phase 9"
#define STR6895_TEXT "SW Code diag. 10"
#define STR6896_TEXT "FA Phase 10"
#define STR6905_TEXT "SW Code diag. 11"
#define STR6906_TEXT "FA Phase 11"
#define STR6915_TEXT "SW Code diag. 12"
#define STR6916_TEXT "FA Phase 12"
#define STR6925_TEXT "SW Code diag. 13"
#define STR6926_TEXT "FA Phase 13"
#define STR6935_TEXT "SW Code diag. 14"
#define STR6936_TEXT "FA Phase 14"
#define STR6945_TEXT "SW Code diag. 15"
#define STR6946_TEXT "FA Phase 15"
#define STR6955_TEXT "SW Code diag. 16"
#define STR6956_TEXT "FA Phase 16"
#define STR6965_TEXT "SW Code diag. 17"
#define STR6966_TEXT "FA Phase 17"
#define STR6975_TEXT "SW Code diag. 18"
#define STR6976_TEXT "FA Phase 18"
#define STR6985_TEXT "SW Code diag. 19"
#define STR6986_TEXT "FA Phase 19"
#define STR6995_TEXT "SW Code diag. 20"
#define STR6996_TEXT "FA Phase 20"
#define STR6800_TEXT "Historique 1 Date/Heure"
#define STR6801_TEXT "Historique 1 Code erreur"
#define STR6802_TEXT "Historique 2 Date/Heure"
#define STR6803_TEXT "Historique 2 Code erreur"
#define STR6804_TEXT "Historique 3 Date/Heure"
#define STR6805_TEXT "Historique 3 Code erreur"
#define STR6806_TEXT "Historique 4 Date/Heure"
#define STR6807_TEXT "Historique 4 Code erreur"
#define STR6808_TEXT "Historique 5 Date/Heure"
#define STR6809_TEXT "Historique 5 Code erreur"
#define STR6810_TEXT "Historique 6 Date/Heure"
#define STR6811_TEXT "Historique 6 Code erreur"
#define STR6812_TEXT "Historique 7 Date/Heure"
#define STR6813_TEXT "Historique 7 Code erreur"
#define STR6814_TEXT "Historique 8 Date/Heure"
#define STR6815_TEXT "Historique 8 Code erreur"
#define STR6816_TEXT "Historique 9 Date/Heure"
#define STR6817_TEXT "Historique 9 Code erreur"
#define STR6818_TEXT "Historique 10 Date/Heure"
#define STR6819_TEXT "Historique 10 Code erreur"
#define STR6900_TEXT "Historique 11 Date/Heure"
#define STR6901_TEXT "Historique 11 Code erreur"
#define STR6910_TEXT "Historique 12 Date/Heure"
#define STR6911_TEXT "Historique 12 Code erreur"
#define STR6920_TEXT "Historique 13 Date/Heure"
#define STR6921_TEXT "Historique 13 Code erreur"
#define STR6930_TEXT "Historique 14 Date/Heure"
#define STR6931_TEXT "Historique 14 Code erreur"
#define STR6940_TEXT "Historique 15 Date/Heure"
#define STR6941_TEXT "Historique 15 Code erreur"
#define STR6950_TEXT "Historique 16 Date/Heure"
#define STR6951_TEXT "Historique 16 Code erreur"
#define STR6960_TEXT "Historique 17 Date/Heure"
#define STR6961_TEXT "Historique 17 Code erreur"
#define STR6970_TEXT "Historique 18 Date/Heure"
#define STR6971_TEXT "Historique 18 Code erreur"
#define STR6980_TEXT "Historique 19 Date/Heure"
#define STR6981_TEXT "Historique 19 Code erreur"
#define STR6990_TEXT "Historique 20 Date/Heure"
#define STR6991_TEXT "Historique 20 Code erreur"
#define STR6820_TEXT "Reset Historique"
#define STR6821_TEXT "Code d'erreur 3"
#define STR6823_2_TEXT "Historique 3 Message d'erreur"
#define STR6825_TEXT "Valeur histo. 3 du diagnostic de dérangement"
#define STR6826_TEXT "Valeur histo. 3 de la phase de dérangement"
#define STR6830_TEXT "Valeur histo. 4 du compteur codes de dérangement"
#define STR6833_TEXT "4ème valeur d'historique du code erreur Albatros"
#define STR6835_TEXT "Valeur histo. 4 du diagnostic de dérangement"
#define STR6836_TEXT "Valeur histo. 4 de la phase de dérangement"
#define STR6840_TEXT "Valeur histo. 5 du compteur codes de dérangement"
#define STR6843_TEXT "5ème valeur d'historique du code erreur Albatros"
#define STR6845_TEXT "Valeur histo. 5 du diagnostic de dérangement"
#define STR6846_TEXT "Valeur histo. 5 de la phase de dérangement"
#define STR7001_TEXT "Signalisation de maintenance"
#define STR7007_TEXT "Configuration / RAZ des messages de maintenance"
#define STR7010_TEXT "Message de maintenance - Acquitter"
#define STR7011_TEXT "Durée de répétition pour messages maintenance"
#define STR7040_TEXT "Heures de fonc. brûleur jusqu'à la maintenance"
#define STR7041_TEXT "Heures de fonct. depuis dernière maintenance"
#define STR7042_TEXT "Limite pour m. en serv. Depuis dernière mainten."
#define STR7043_TEXT "Mises en service depuis dernière maintenance"
#define STR7044_TEXT "Limite des mois depuis la dernière maintenance"
#define STR7045_TEXT "Mois depuis dernière maintenance"
#define STR7050_TEXT "Limite vitesse rot. ventil. Pour message maint."
#define STR7051_TEXT "Signalis. maintenance courant ionisation"
#define STR8000_TEXT "Etat du circuit de chauffage 1"
#define STR8001_TEXT "Etat du circuit de chauffage 2"
#define STR8003_TEXT "Etat de l'ECS"
#define STR8005_TEXT "Etat de la chaudière"
#define STR8007_TEXT "Etat équipement solaire"
#define STR8310_TEXT "T° de chaudière"
#define STR8311_TEXT "Consigne de T° de chaudière"
#define STR8314_TEXT "T° de retour"
#define STR8316_TEXT "T° fumées"
#define STR8324_TEXT "Vitesse du ventilateur"
#define STR8325_TEXT "Commande du ventilateur"
#define STR8326_TEXT "Puissance relative"
#define STR8328_TEXT "Affichage de régime coffret"
#define STR2730_TEXT "Valeur mesurée du courant d'ionisation"
#define STR8336_TEXT "Heures de fonctionnement"
#define STR8337_TEXT "Compteur de démarrages brûleur"
#define STR8338_TEXT "Heures de fonctionnement en mode chauffage"
#define STR8339_TEXT "Heures de fonctionnement en mode ECS"
#define STR8340_TEXT "Heures de fonctionnement en demande chaud ext."
#define STR8510_TEXT "T° mesurée capteur solaire 1 (B6)"
#define STR8530_TEXT "Heures de fonctionnement production solaire"
#define STR8700_TEXT "T° extérieure locale"
#define STR8703_TEXT "T° extérieure résultante"
#define STR8704_TEXT "T° extérieure mélangée"
#define STR8721_TEXT "T° ambiante"
#define STR8740_TEXT "T° ambiante 1"
#define STR8741_TEXT "Consigne actuelle de T° Ambiante"
#define STR8743_TEXT "T° de départ circuit de chauffe 1"
#define STR8744_TEXT "Consigne de départ H1"
#define STR8750_TEXT "Vitesse pompe"
#define STR8770_TEXT "T° ambiante 2"
#define STR8771_TEXT "Consigne actuelle de T° ambiante CC2"
#define STR8773_TEXT "T° de départ circuit de chauffe 2"
#define STR8774_TEXT "Consigne de départ H2"
#define STR8830_TEXT "T°  mesurée ECS en haut (B3)"
#define STR8831_TEXT "Consigne actuelle de T° ECS"
#define STR8836_TEXT "T° de charge ECS"
#define STR8950_TEXT "Signal de processus départ segment"
#define STR8952_TEXT "Signal de processus retour segment"
#define STR8980_TEXT "Températ. accumlateur mesurée partie haute (B4)"
#define STR9500_TEXT "Temps de préventilation"
#define STR9502_TEXT "Modulation de l'air dans la préventilation"
#define STR9504_TEXT "Vitesse ventilateur dans la préventilation"
#define STR9510_TEXT "Modulation d'air en charge d'allumage"
#define STR9512_TEXT "Vitesse de rotation ventil. en charge d'allumage"
#define STR9520_TEXT "Modulation d'air en charge partielle"
#define STR9522_TEXT "Modulation d'air en pleine charge"
#define STR9524_TEXT "Consigne vitesse rotation en charge partielle"
#define STR9527_TEXT "Consigne vitesse rotation ventil. Pleine charge"
#define STR9540_TEXT "Temps de post-ventilation"
#define STR9560_TEXT "Mod. Ventil. Pour charge balllon  stratification"
#define STR9563_TEXT "Consigne ventil. Charge continue ballon  stratif"
#define STR15004_TEXT "T° départ après mélangeur"
#define STR15009_TEXT "Bouton rotatif"
#define STR15011_TEXT "Touche de présence"
#define STR15012_TEXT "Jours de vacances restants"
#define STR15019_TEXT "Période de chauffe 1 Lundi Début"
#define STR15020_TEXT "Période de chauffe 1 Lundi Fin"
#define STR15021_TEXT "Période de chauffe 2 Lundi Début"
#define STR15022_TEXT "Période de chauffe 2 Lundi Fin"
#define STR15023_TEXT "Période de chauffe 3 Lundi Début"
#define STR15024_TEXT "Période de chauffe 3 Lundi Fin"
#define STR15025_TEXT "Période de chauffe 1 Mardi Début"
#define STR15026_TEXT "Période de chauffe 1 Mardi Fin"
#define STR15027_TEXT "Période de chauffe 2 Mardi Début"
#define STR15028_TEXT "Période de chauffe 2 Mardi Fin"
#define STR15029_TEXT "Période de chauffe 3 Mardi Début"
#define STR15030_TEXT "Période de chauffe 3 Mardi Fin"
#define STR15031_TEXT "Période de chauffe 1 Mercredi Début"
#define STR15032_TEXT "Période de chauffe 1 Mercredi Fin"
#define STR15033_TEXT "Période de chauffe 2 Mercredi Début"
#define STR15034_TEXT "Période de chauffe 2 Mercredi Fin"
#define STR15035_TEXT "Période de chauffe 3 Mercredi Début"
#define STR15036_TEXT "Période de chauffe 3 Mercredi Fin"
#define STR15037_TEXT "Période de chauffe 1 Jeudi Début"
#define STR15038_TEXT "Période de chauffe 1 Jeudi Fin"
#define STR15039_TEXT "Période de chauffe 2 Jeudi Début"
#define STR15040_TEXT "Période de chauffe 2 Jeudi Fin"
#define STR15041_TEXT "Période de chauffe 3 Jeudi Début"
#define STR15042_TEXT "Période de chauffe 3 Jeudi Fin"
#define STR15043_TEXT "Période de chauffe 1 Vendredi Début"
#define STR15044_TEXT "Période de chauffe 1 Vendredi Fin"
#define STR15045_TEXT "Période de chauffe 2 Vendredi Début"
#define STR15046_TEXT "Période de chauffe 2 Vendredi Fin"
#define STR15047_TEXT "Période de chauffe 3 Vendredi Début"
#define STR15048_TEXT "Période de chauffe 3 Vendredi Fin"
#define STR15049_TEXT "Période de chauffe 1 Samedi Début"
#define STR15050_TEXT "Période de chauffe 1 Samedi Fin"
#define STR15051_TEXT "Période de chauffe 2 Samedi Début"
#define STR15052_TEXT "Période de chauffe 2 Samedi Fin"
#define STR15053_TEXT "Période de chauffe 3 Samedi Début"
#define STR15054_TEXT "Période de chauffe 3 Samedi Fin"
#define STR15055_TEXT "Période de chauffe 1 Dimanche Début"
#define STR15056_TEXT "Période de chauffe 1 Dimanche Fin"
#define STR15057_TEXT "Période de chauffe 2 Dimanche Début"
#define STR15058_TEXT "Période de chauffe 2 Dimanche Fin"
#define STR15059_TEXT "Période de chauffe 3 Dimanche Début"
#define STR15060_TEXT "Période de chauffe 3 Dimanche Fin"
#define STR15061_TEXT "Heure chaudière"
#define STR15062_TEXT "Modèle de sonde d'ambiance QAA"
#define STR15064_TEXT "T° cible"
#define STR15066_TEXT "Chauffage manuel"
#define STR15067_TEXT "Connexion interrompue"
#define STR99999_TEXT "Code commande INCONNU"

#define ENUM20_01_TEXT "English"
#define ENUM20_02_TEXT "Deutsch"
#define ENUM20_03_TEXT "Français"
#define ENUM20_04_TEXT "Nederlands"
#define ENUM20_05_TEXT "Italiano"
#define ENUM20_06_TEXT "Español"
#define ENUM20_07_TEXT "Polski"
#define ENUM20_08_TEXT "Ceski"
#define ENUM22_01_TEXT "Temporaire"
#define ENUM22_02_TEXT "Permanent"
#define ENUM23_00_TEXT "Code"
#define ENUM23_01_TEXT "Code et Texte"
#define ENUM28_01_TEXT "Sauvegarde automatique"
#define ENUM28_02_TEXT "Sauvegarde après confirmation"
#define ENUM29_01_TEXT "°C,bar"
#define ENUM29_02_TEXT "°F,PSI"
#define ENUM40_00_TEXT "Unité d'ambiance 1"
#define ENUM40_01_TEXT "Unité d'ambiance 2"
#define ENUM40_02_TEXT "Unité d'ambiance P"
#define ENUM40_03_TEXT "Unité de contrôle 1"
#define ENUM40_04_TEXT "Unité de contrôle 2"
#define ENUM40_05_TEXT "Unité de service"
#define ENUM42_01_TEXT "Circuit de chauffage 1 et 2"
#define ENUM42_02_TEXT "Circuit de chauffage 1 et P"
#define ENUM42_03_TEXT "Tous les circuits de chauffage"
#define ENUM44_01_TEXT "Ensemble avec circuit de chauffage 1"
#define ENUM44_02_TEXT "Indépendamment"
#define ENUM47_02_TEXT "Pour tous les circuits de chauffage attribués"
#define ENUM48_00_TEXT "Non"
#define ENUM48_03_TEXT "Ensemble"
#define ENUM130_00_TEXT "Absent"
#define ENUM130_01_TEXT "Opérationnel"
#define ENUM130_02_TEXT "Pas de signal"
#define ENUM130_03_TEXT "Changer la pile"
#define ENUM648_00_TEXT "Hors gel"
#define ENUM648_01_TEXT "Réduit"
#define ENUM700_01_TEXT "Auto"
#define ENUM700_03_TEXT "Confort"
#define ENUM702_01_TEXT "Programme de chauffage 1"
#define ENUM702_03_TEXT "Programme normal"
#define ENUM702_04_TEXT "Inconnue"
#define ENUM702_05_TEXT "Programme de chauffage 2"
#define ENUM702_06_TEXT "Programme de chauffage 3"
#define ENUM703_00_TEXT "Présent"
#define ENUM703_01_TEXT "Absent"
#define ENUM780_01_TEXT "Jusqu'à la consigne réduite"
#define ENUM780_02_TEXT "Jusqu'à la consigne hors gel"
#define ENUM832_00_TEXT "2 points"
#define ENUM832_01_TEXT "3 points"
#define ENUM850_01_TEXT "Chauffage fonctionnel"
#define ENUM850_05_TEXT "Manuel"
#define ENUM861_01_TEXT "Mode chauffage"
#define ENUM861_02_TEXT "Toujours"
#define ENUM880_00_TEXT "Niveau de fonctionnement"
#define ENUM880_01_TEXT "Courbe"
#define ENUM880_02_TEXT "Course de T° nominale"

#define ENUM_ERROR_1e_TEXT "Erreur du capteur de T° de départ 1"

#define ENUM_WEEKDAY_01_TEXT "Lundi"
#define ENUM_WEEKDAY_02_TEXT "Mardi"
#define ENUM_WEEKDAY_03_TEXT "Mercredi"
#define ENUM_WEEKDAY_04_TEXT "Jeudi"
#define ENUM_WEEKDAY_05_TEXT "Vendredi"
#define ENUM_WEEKDAY_06_TEXT "Samedi"
#define ENUM_WEEKDAY_07_TEXT "Dimanche"
